apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-liveness
  labels:
    app: simple-liveness
    
spec:
  selector:
    matchLabels:
      app: simple-liveness
  template:
    metadata:
      labels:
        app: simple-liveness
    spec:
      containers:
      - name: simple-liveness # Name of container in the pod.
        image: kamranazeem/k8s-probes-demo:latest
        imagePullPolicy: IfNotPresent

        env:
        - name: START_DELAY
          value: "30" # Double quotes for ENV variables are important.

        ports:
        - name: http 
          containerPort: 80

        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 5m
            memory: 20Mi
       
        # Liveliness probes are used while the container is up, 
        #   to see if the service is "still" alive.
        # If the service does not respond, then kubernetes kills the container/pod,
        #   and restarts it.
        # It is therefore important to have initialDelaySeconds for the "livenessProbe"
        #   to be as late as possible.
        # If it is a small number, and if for some reason container is not started yet,
        #   (in case of slow application startup), then kubernetes will restart it.
        # This means the pod will stuck in a crash loop, and will never start.
        # Remember, livenessProbe does NOT start AFTER readiness probe.
        #   In-fact, they both start at the same time.
        # Liveness probe will vary from application to application. 
        #   Some start fast, some start slow.
        livenessProbe:
          httpGet:
            path: /livenesscheck.txt
            port: 80
          initialDelaySeconds: 5
          # Retry the probe every X seconds (frequency):
          periodSeconds: 3
          # Number of times this probe can fail,
          #   before kubernetes gives up and "restarts" the "container":
          failureThreshold: 1

---

apiVersion: v1
kind: Service
metadata:
  name: simple-liveness
  labels:
    app: simple-liveness
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: simple-liveness
