apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-demo
  labels:
    app: probes-demo
    
spec:
  selector:
    matchLabels:
      app: probes-demo
  template:
    metadata:
      labels:
        app: probes-demo
    spec:
      containers:
      - name: troublemaker # Name of container in the pod.
        image: kamranazeem/k8s-probes-demo:latest
        imagePullPolicy: Always

        # Notes: 
        # * ENTRYPOINT in Docker = 'command' in k8s
        # * CMD in Docker = 'args' in k8s 
        # * If you provide "command", then you also need to provide "args".
        #     For some reason the CMD defined in the container image is ignored,
        #     when k8s "command" is specified.
        command: ["/troublemaker.sh"]
        args: ["nginx", "-g", "daemon off;"]

        env:
        # Double quotes for values of ENV variables are important.
        - name: ROLE
          #value: "NORMAL"
          value: "TROUBLEMAKER"

        volumeMounts:
        - name: shared-directory
          mountPath: /shared
        
        ports:
        - name: alt-http
          containerPort: 8888

        resources:
          limits:
            cpu: 10m
            memory: 8Mi
          requests:
            cpu: 5m
            memory: 4Mi
          
      - name: probes-demo # Name of container in the pod.
        image: kamranazeem/k8s-probes-demo:latest
        imagePullPolicy: Always

        env:
        - name: START_DELAY
          value: "10" # Double quotes for ENV variables are important.

        ports:
        - name: http 
          containerPort: 80

        resources:
          limits:
            cpu: 10m
            memory: 8Mi
          requests:
            cpu: 5m
            memory: 4Mi

        # Readiness probes help Kubernetes know when to start sending traffic to the pod.
        #   This probe helps kubernetes to "add" or "remove" this pod from the service in front of it.
        #   So, when the probe passes it is added to the service,
        #       when it fails at any time in it's life, kubernetes removes it from the service.
        # Restarting the "stuck" container is the job of livenessProbe, explained further down.
        # Note: Readiness probe runs throughout the life of the container - every "periodSeconds",
        #       not just at the container start time!
        #
        # The WITPASS/wordpress images takes long to start, 
        #   because themes and plugins are pulled at container start time.
        # 
        readinessProbe:
          httpGet:
            path: /readiness.txt
            port: 80
          initialDelaySeconds: 5

          # Retry the probe every X seconds (frequency):
          periodSeconds: 2

          # Number of times this probe can fail ,
          #   before kubernetes gives up and marks the "pod" as "Unready":
          failureThreshold: 24

          # In the case above, the Pod will be marked "Unready",
          #   if the probe does not pass 5 x 24 = 120 seconds.
          successThreshold: 1
        
        # Liveliness probes are used while the container is up, 
        #   to see if the service is "still" alive.
        # If the service does not respond, then kubernetes kills the container/pod,
        #   and restarts it.
        # It is therefore important to have initialDelaySeconds for the "livenessProbe"
        #   to be as late as possible.
        # If it is a small number, and if for some reason container is not started yet,
        #   (in case of slow application startup), then kubernetes will restart it.
        # This means the pod will stuck in a crash loop, and will never start.
        # Remember, livenessProbe does NOT start AFTER readiness probe.
        #   In-fact, they both start at the same time.
        # Liveness probe will vary from application to application. 
        #   Some start fast, some start slow.
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 300
          # Retry the probe every X seconds (frequency):
          periodSeconds: 10
          # Number of times this probe can fail,
          #   before kubernetes gives up and "restarts" the "container":
          failureThreshold: 1
        volumeMounts:
        - name: shared-directory
          mountPath: /usr/share/nginx/html

      volumes:
      - name: shared-directory
        emptyDir: {}
